package tests;// Generated by Selenium IDE

import model.GroupData;
import org.junit.jupiter.api.Test;

public class GroupCreationTests extends TestBase {



    @Test
    public void canCreateGroup() {
        app.groups().createGroup(new GroupData("Group name", "Group header", "Group footer") );
    }


    @Test
    public void canCreateGroupWithEmptyName() {
        app.groups().createGroup(new GroupData() );
    }

    @Test
    public void canCreateGroupWithNameOnly() {
        app.groups().createGroup(new GroupData().withName("Test some") );
    }

}
